### ISSUE TITLE
redis на другом хосте

### ISSUE THREAD

**Issue by schmel** [centosadmin/redmine_intouch#113]
Где в коде можно указать редис на другой хост? сейчас в логах ругается на 
```
Redis::CannotConnectError (Error connecting to Redis on 127.0.0.1:6379 (Errno::ECONNREFUSED)):
  redis (4.0.3) lib/redis/client.rb:350:in `rescue in establish_connection'
  redis (4.0.3) lib/redis/client.rb:334:in `establish_connection'
```
на localhost нет возможности поставить, все в докере запускается. supervisord не рассматриваю.

**Comment by schmel** [comment]
хм, это в sidekiq плагине настраивается. 
решилось установкой переменнной ENV REDIS_URL=redis://redis:6379 в Dockerfile
