### ISSUE TITLE
undefined method `default_users_hide_mail?'

### ISSUE THREAD

**Issue by mr-exz** [centosadmin/redmine_intouch#15]
```
ActionView::Template::Error (undefined method `default_users_hide_mail?' for #<Class:0x00000002ad1180>
Did you mean?  default_projects_modules?):
    11: <%= favicon %>
    12: <%= stylesheet_link_tag 'jquery/jquery-ui-1.11.0', 'application', 'responsive', :media => 'all' %>
    13: <%= stylesheet_link_tag 'rtl', :media => 'all' if l(:direction) == 'rtl' %>
    14: <%= javascript_heads %>
    15: <%= heads_for_theme %>
    16: <%= call_hook :view_layouts_base_html_head %>
    17: <!-- page specific tags -->
  app/models/user_preference.rb:29:in `initialize'
  app/models/user.rb:898:in `pref'
```

**Comment by arturtr** [comment]
This is not our plugin issue.

**Comment by mr-exz** [comment]
ok
