### ISSUE TITLE
500 Internal server error

### ISSUE THREAD

**Issue by hatsnal** [centosadmin/redmine_intouch#64]
Пытаюсь инициализировать бота в в ответ получаю: **500 Internal server error**

 В логах:

> POST "/intouch/bot_init" for 192.168.62.234 at 2018-02-02 17:12:35 +0500
> Processing by IntouchController#bot_init as HTML
>   Parameters: {"authenticity_token"=>"wsg2m03gEiYQDUTw7h6iVWfNGtEav+G95E58xyxYg3G2FGnPtkVMhC7pYgsmiaxhVqdPWWHmzogEAdeSKhLxtw=="}
>   Current user: admin (id=1)
> Completed 500 Internal Server Error in 334ms (ActiveRecord: 2.2ms)
> 
> Telegram::Bot::Exceptions::ResponseError (Telegram API has returned the error. (ok: "false", error_code: "404", description: "Not Found")):
>   plugins/redmine_intouch/app/controllers/intouch_controller.rb:20:in `bot_init'
>   lib/redmine/sudo_mode.rb:63:in `sudo_mode'

Бот живой, токен бота пробовал указывать так же в формате botXXXX

**Comment by hatsnal** [comment]
Разобрался можно закрыть.
